name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.TOKEN}}
          tap: subtlemuffin/formulas
          formula: clang-tidy
          tag: ${{github.ref}}
          revision: ${{github.sha}}
          force: false # true
